<br /><br />
<div id="view-content">
	<p>View script for controller <b>Index</b> and script/action name <b>login</b></p>
</div>
<div class="bottom_login_links">
	<div class="left_links">
		Don't have a Nyrix account?
		<br />
		<a href="#">- Register Now -</a>
	</div>
	<div class="right_links">
		Having troubles logging in?<br />
		<a onclick="unavailable()">- <strike>Password Recovery</strike> -</a>
	</div>
</div>